package com.example.booksornothing.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFF13D7A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9CF985)
val md_theme_light_onPrimaryContainer = Color(0xFF012200)
val md_theme_light_secondary = Color(0xFF006879)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFAAEDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F26)
val md_theme_light_tertiary = Color(0xFFF1FAE7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF9AF7AA)
val md_theme_light_onTertiaryContainer = Color(0xFF00210A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF380036)
val md_theme_light_surface = Color(0xFFF8F8F8)
val md_theme_light_onSurface = Color(0xFF380036)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF6210F1)
val md_theme_light_inverseOnSurface = Color(0xFFFFEBF7)
val md_theme_light_inverseSurface = Color(0xFF551251)
val md_theme_light_inversePrimary = Color(0xFF81DC6C)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0F6E06)
val md_theme_light_outlineVariant = Color(0xFFC3C8BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF81DC6C)
val md_theme_dark_onPrimary = Color(0xFF013A00)
val md_theme_dark_primaryContainer = Color(0xFF035300)
val md_theme_dark_onPrimaryContainer = Color(0xFF9CF985)
val md_theme_dark_secondary = Color(0xFF28D8F9)
val md_theme_dark_onSecondary = Color(0xFF003640)
val md_theme_dark_secondaryContainer = Color(0xFF004E5C)
val md_theme_dark_onSecondaryContainer = Color(0xFFAAEDFF)
val md_theme_dark_tertiary = Color(0xFF7EDA90)
val md_theme_dark_onTertiary = Color(0xFF003916)
val md_theme_dark_tertiaryContainer = Color(0xFF005323)
val md_theme_dark_onTertiaryContainer = Color(0xFF9AF7AA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF380036)
val md_theme_dark_onBackground = Color(0xFFFFD7F4)
val md_theme_dark_surface = Color(0xFF380036)
val md_theme_dark_onSurface = Color(0xFFFFD7F4)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF380036)
val md_theme_dark_inverseSurface = Color(0xFFFFD7F4)
val md_theme_dark_inversePrimary = Color(0xFF0F6E06)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF81DC6C)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF76D062)
